In [10]:
import torch
from tensorflow.python.autograph.lang.special_functions import tensor_list
from tensorflow.python.autograph.pyct.static_analysis.reaching_fndefs import resolve

x = torch.arange(12)
print(x)

x = x.reshape(3, 4)
print(x)

x = torch.zeros((2, 3, 4))
print(x)

x = torch.ones((2, 3, 4))
print(x)

x = torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
print(x)

x = torch.tensor([1,0,2,4,8])
y = torch.tensor([2,2,2,2])

# x = torch.arange(12, dtype=torch.float32),rehape((3,4))
y = torch.tensor([[2,0,1,4], [1,2,3,4],[4,3,2,1]])

# x = x.sum()
# print(x)

# a =torch.arange(3), reshape((1,3))
# print(a)

# x[-1],x[1:3]

# x[0:2,:] = 12
# x


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
